# Ghulam Haider
Roll No PIAIC88463

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
AR1 = np.arange(10)
AR2 = AR1.reshape(2,5)
AR2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
ARR1 = np.arange(10).reshape(2,5)

ARR2 = np.ones(10,int).reshape(2,5)
V_ARR= np.vstack([ARR1,ARR2])
V_ARR

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
ARR1 = np.arange(10).reshape(2,5)
ARR2 = np.ones(10,int).reshape(2,5)
H_AAR= np.hstack([ARR1,ARR2])
H_AAR

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
p = np.arange(10).reshape(2,5)
print(p,'\n')
q = p.flatten()
q

[[0 1 2 3 4]
 [5 6 7 8 9]] 



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
x = np.arange(15).reshape(5,3)
print(x,'\n')
z = x.flatten()
z

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
r = np.arange(15)
print(r,'\n')
s = r.reshape(5,3)
s

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
M = np.arange(25).reshape(5,5)
print(M,'\n')
np.square(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 



array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
h = np.arange(30).reshape(5,6)
print(h,'\n')
h_mean = np.mean(h)
print("Mean of array: ",h_mean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

Mean of array:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
h_std = np.std(h)
print("Standard Dev of array: ",h_std)

Standard Dev of array:  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [10]:
h_median = np.median(h)
print("Median of array: ",h_median)

Median of array:  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
h.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
f = np.arange(16).reshape(4,4)
print(f,'\n')
print("sum of diagonal elements is: ",np.trace(f))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

sum of diagonal elements is:  30


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
from numpy.linalg import det
D = np.arange(10,26).reshape(4,4)
print(D,'\n')
det(D)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]] 



8.067895621578512e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
Ar = np.arange(0,200)
print(Ar,'\n')
print()
print("{0} - is the 5th percentile".format(round(np.percentile(Ar,5),2)))
print("{0} - is the 95th percentile".format(round(np.percentile(Ar,95),2)))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199] 


9.95 - is the 5th percentile
189.05 - is the 95th percentile


## Question:15

### How to find if a given array has any null values?

In [15]:
g = np.arange(5)
print(g)
print(np.isnan(g).any(),'\n')
n = np.array([40,np.nan,50])
print(n)
print(np.isnan(n).any())

[0 1 2 3 4]
False 

[40. nan 50.]
True
