# Ghulam Haider 
Roll No PIAIC88463

Batch Batch 7

# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
b= np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
b.shape

(40,)

5. Print the type of the previous array in question 3

In [6]:
print(type(b))
b.dtype

<class 'numpy.ndarray'>


dtype('int32')

6. Print the numpy version and the configuration


In [7]:
print('numpy version is ',np.__version__)

np.show_config()


numpy version is  1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/abc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/abc/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/abc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\w

7. Print the dimension of the array in question 3


In [8]:
b.ndim 

1

8. Create a boolean array with all the True values

In [9]:
bool=b>0
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [10]:
a2= np.array([[0,1,2],[2,1,0]])
print(a2,'\n')
print('verification',a2.ndim)

[[0 1 2]
 [2 1 0]] 

verification 2


10. Create a three dimensional array



In [11]:
a3 = np.array([[[0,1,2],
                 [2,1,0]]])
print(a3,'\n')
print('verification ',a3.ndim)

[[[0 1 2]
  [2 1 0]]] 

verification  3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
vec = np.arange(9,45,9)  
print('Orginal vector',vec,'\n\n')

rev_vec = vec[::-1]
print('Reverse vector',rev_vec)

Orginal vector [ 9 18 27 36] 


Reverse vector [36 27 18  9]


12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
null_vector = np.zeros(10)
print(null_vector,'\n\n')
null_vector[4] = 1        
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [14]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)


f_arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(f_arr.dtype)

int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arra = np.array([[5, 8, 5], [2, 3,5]]) 
arrb = np.array([[0, 2,6], [3, 2, 7]])

print(arra*arrb)

[[ 0 16 30]
 [ 6  6 35]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 

17. Extract all odd numbers from arr with values(0-9)

In [18]:

num = np.arange(10)
print(num)



print(num[num % 2 == 1])

# OR

print(num[num % 2 != 0])


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [19]:

num = np.arange(10)
print(a,'\n')


num[num % 2 == 1] = -1

print(num)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
arr = np.arange(10)
print(arr,'\n')
arr[5:9] = 12

print(arr)

[0 1 2 3 4 5 6 7 8 9] 

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [21]:
ar2 = np.ones((6,6), dtype=int)
print(ar2,'\n')

ar2[1:-1,1:-1] = 0
print(ar2)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[1][1] = 12
print(arr2d,'\n')
# OR
arr2d[1,1] = 12
arr2d


[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]] 



array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d,'\n\n\n')

arr3d[:1,0:2] = 64
print(arr3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
Array2D = np.arange(9).reshape(3,3)
print(Array2D,'\n\n\n')

Array1D = Array2D[0]
print(Array1D)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [26]:
Array2D = np.arange(9).reshape(3,3)
print(Array2D,'\n\n')

V2= Array2D[1][1]
print('2nd value from 2nd 1-D array is:',V2)


[[0 1 2]
 [3 4 5]
 [6 7 8]] 


2nd value from 2nd 1-D array is: 4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [27]:
Array2D = np.arange(9).reshape(3,3)
print(Array2D,'\n\n\n')

C3 = Array2D[:2,2:]
print(C3)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



[[2]
 [5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
rand_array = np.random.random((10,10))
print(rand_array,'\n\n\n')
print("max = ",rand_array.max(),"\n\nmin = ",rand_array.min())

[[0.02981876 0.20297869 0.65903637 0.52977642 0.19193607 0.64392047
  0.39291049 0.84039985 0.3843914  0.24630995]
 [0.86500822 0.24332641 0.6837524  0.56378572 0.39505859 0.2011172
  0.6665211  0.87664843 0.9040151  0.00945115]
 [0.81004295 0.81151016 0.50355687 0.48785439 0.4953021  0.65051092
  0.49078512 0.38465073 0.77371907 0.37159792]
 [0.11738514 0.39997755 0.48214301 0.64326422 0.85295199 0.10780885
  0.60946503 0.49839264 0.69787479 0.6065111 ]
 [0.0211702  0.06934626 0.87249321 0.16796268 0.43734814 0.3960016
  0.46924108 0.8268858  0.78328896 0.53526099]
 [0.50595048 0.65658986 0.93217029 0.48892641 0.7921316  0.27413316
  0.59921695 0.41232097 0.37488837 0.97026854]
 [0.77104376 0.75763505 0.34688839 0.30484723 0.57676008 0.2325111
  0.74983245 0.70632639 0.94723555 0.17830514]
 [0.58961211 0.46594677 0.99936947 0.97493485 0.46419467 0.92516882
  0.87290703 0.03946037 0.03629505 0.04950923]
 [0.59602645 0.63446661 0.39607155 0.65497639 0.75227974 0.00489706
  0.17617699 0.

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("common items between a and b are ",np.intersect1d(a,b))

common items between a and b are  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

data[names != "Will"]

array([[ 0.80406004,  1.23259937,  1.35870693, -0.53288318],
       [-0.74370175, -1.20991496, -0.72429431,  0.42502368],
       [ 1.66020088,  0.30608629,  0.2151345 ,  0.50332217],
       [ 0.4029293 ,  1.27593817,  1.36954065,  0.40527514],
       [-0.30981768, -0.62857155,  1.55740681,  0.13182411]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[-0.6506266 ,  2.10986214, -0.22897431,  0.97192281],
       [ 0.73672923,  0.64621089,  0.71307755, -1.51857752],
       [-2.34132974, -0.10789472, -2.51432663,  1.00135301],
       [-1.21681797,  0.93610421,  0.41909859, -0.75453603],
       [ 0.71698949,  1.36454443,  1.63230296, -2.20383975],
       [-1.58174136,  1.25230704, -0.80200853,  0.05619118],
       [-1.22903677,  0.6453412 , -0.0033943 ,  1.69446994]])

In [33]:
print(names == "Will")
print(names == "Joe")

L = (names == "Will") | (names == "Joe")
print(names[ L])
print(data[L])

print('\n',names[~ L])
print(data[~L])

[False False  True False  True False False]
[False  True False False False  True  True]
['Joe' 'Will' 'Will' 'Joe' 'Joe']
[[ 0.73672923  0.64621089  0.71307755 -1.51857752]
 [-2.34132974 -0.10789472 -2.51432663  1.00135301]
 [ 0.71698949  1.36454443  1.63230296 -2.20383975]
 [-1.58174136  1.25230704 -0.80200853  0.05619118]
 [-1.22903677  0.6453412  -0.0033943   1.69446994]]

 ['Bob' 'Bob']
[[-0.6506266   2.10986214 -0.22897431  0.97192281]
 [-1.21681797  0.93610421  0.41909859 -0.75453603]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
Arr2d = np.arange(1,16).reshape(5,3)
Arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [35]:
Z = np.arange(1,17).reshape(2,2,4)
print(Z,)
print('\n\nshape: ',Z.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


shape:  (2, 2, 4)


33. Swap axes of the array you created in Question 32

In [36]:
np.swapaxes(Z,0,1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [37]:
C= np.arange(10)
print(C,'\n\n')

print(np.sqrt(C))

[0 1 2 3 4 5 6 7 8 9] 


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:
M = np.random.randn(12)
print('M = ',M )

N = np.random.randn(12)
print('\nN = ',N)

O=np.maximum(M,N)
print('\n maximum values array',O)

M =  [-0.20255401  0.34306003 -0.04944331 -1.39932312 -1.58938983 -1.94533409
  0.37303663 -1.22055246 -0.36133999 -0.86456168 -1.05330732 -0.08177283]

N =  [ 1.5248444  -0.82516463 -1.19160076  0.60474711 -0.89060438 -0.27092312
 -0.53005611  0.48555993 -0.943503   -0.56631204 -1.54158375  0.24219783]

 maximum values array [ 1.5248444   0.34306003 -0.04944331  0.60474711 -0.89060438 -0.27092312
  0.37303663  0.48555993 -0.36133999 -0.56631204 -1.05330732  0.24219783]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [39]:
Names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
u_a_s=np.unique(np.sort(Names))
print(u_a_s)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [40]:
a = np.array([1,2,3,4,5])
print(a,'\n')
b = np.array([5,6,7,8,9])
print(b,'\n')
a = np.setdiff1d(a,b)
print('after removing a becomes',a)

[1 2 3 4 5] 

[5 6 7 8 9] 

after removing a becomes [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [41]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print(sampleArray,'\n\n')

sampleArray=np.delete(sampleArray,np.s_[1:2],axis=1)
sampleArray=np.insert(sampleArray,1,newColumn,axis=1)

print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]] 


[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [42]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x,'\n\n',y)
print('\n',np.dot(x,y))

[[1. 2. 3.]
 [4. 5. 6.]] 

 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [43]:
R=np.random.randn(20)
R.cumsum()

array([-0.49169029,  0.05537245,  0.54429654,  0.85494433, -0.42695172,
       -0.59276638, -1.50885801, -1.03083178, -2.58116146, -2.48529302,
       -3.73623019, -2.82410236, -4.32200885, -3.4144887 , -4.1883661 ,
       -4.98449693, -4.22452088, -3.97570609, -2.64302189, -1.64110173])